---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
    - recipe[java::default]
    - recipe[confluent-cookbook::default]
    - recipe[confluent-cookbook::zookeeper]
    - recipe[confluent-cookbook::kafka]
    attributes: {
      java: {
        install_flavor: "oracle",
        jdk_version: "8",
        oracle: {
          accept_oracle_download_terms: true
        }
      }
    }
